GamingRoom/Models/Venues.cs
namespace GamingRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Venues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venues()
        {
            Events = new HashSet<Events>();
        }

        [Key]
        public int VenueID { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public string Photo { get; set; }


        [Required]
        [StringLength(500)]
        public string Address { get; set; }

        public int? Capacity { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
    }
}

GamingRoom/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamingRoom.Models;

namespace GamingRoom.Controllers
{

    [Authorize(Roles = "SuperAdmin")]

    public class VenuesController : Controller
    {
        private ModelDBContext db = new ModelDBContext();

        // GET: Venues
        public ActionResult Index()
        {
            return View(db.Venues.ToList());
        }

        // GET: Venues/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venues venues = db.Venues.Find(id);
            if (venues == null)
            {
                return HttpNotFound();
            }
            return View(venues);
        }

        // GET: Venues/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VenueID,Name,Address,Capacity")] Venues venues, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/ImgVenues"), fileName);
                    image.SaveAs(path);
                    venues.Photo = fileName;
                }

                db.Venues.Add(venues);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(venues);
        }

        // GET: Venues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venues venues = db.Venues.Find(id);
            if (venues == null)
            {
                return HttpNotFound();
            }
            return View(venues);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VenueID,Name,Address,Capacity,ImageFileName")] Venues venues, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var venueToUpdate = db.Venues.Find(venues.VenueID);

                if (venueToUpdate == null)
                {
                    return HttpNotFound();
                }

                // Aggiorna le proprietà di venueToUpdate
                venueToUpdate.Name = venues.Name;
                venueToUpdate.Address = venues.Address;
                venueToUpdate.Capacity = venues.Capacity;

                // Aggiorna l'immagine solo se ne viene fornita una nuova
                if (image != null && image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/ImgVenues"), fileName);
                    image.SaveAs(path);
                    venueToUpdate.Photo = fileName;
                }

                // Se non viene fornita una nuova immagine, conserva quella esistente
                else
                {
                    venueToUpdate.Photo = venueToUpdate.Photo;
                }

                db.Entry(venueToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venues);
        }



        // GET: Venues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venues venues = db.Venues.Find(id);
            if (venues == null)
            {
                return HttpNotFound();
            }
            return View(venues);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var venue = db.Venues.Include(v => v.Events).FirstOrDefault(v => v.VenueID == id);

            // Controlla se il luogo è associato a un evento
            if (venue != null && venue.Events.Any())
            {
                // Imposta il messaggio di errore
                TempData["ErrorMessage"] = "Non è possibile eliminare l'arena perché è associata a uno o più eventi.";
                return RedirectToAction("Delete", new { id = id });
            }

            db.Venues.Remove(venue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GamingRoom/Views/Venues/Create.cshtml
@model GamingRoom.Models.Venues

@{
    ViewBag.Title = "Create Venue";
}

<h2 class="text-center">Crea Arena</h2>

@using (Html.BeginForm("Create", "Venues", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal ms-5", @style = "height:100vh", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group text-white">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Name -->
        <div class="form-group">
            <div class="ms-3">Nome Arena</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Address -->
        <div class="form-group">
            <div class="ms-3">Indirizzo</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Capacity -->
        <div class="form-group">
            <div class="ms-3">Capacità</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Image Upload -->
        <div class="form-group">
            <div class="ms-3">Immagine</div>
            <div class="col-md-10">
                <input type="file" name="image" class="form-control" />
            </div>
        </div>

        <!-- Submit Button -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crea" class="btn btn-primary" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Torna alla Lista", "Index", null, new { @class = "btn btn-default text-white" })
        </div>

    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamingRoom/Views/Venues/Delete.cshtml
@model GamingRoom.Models.Venues

@{
    ViewBag.Title = "Elimina Arena";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="min-height:100vh">
    <div class="row justify-content-center align-items-center" style="height:100%">
        <div class="col-md-8">
            <div class="card mt-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Elimina Arena</h2>
                </div>
                <div class="card-body">
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger">
                            @TempData["ErrorMessage"]
                        </div>
                    }
                    <h3 class="text-center text-white">Sei sicuro di voler eliminare questo luogo?</h3>
                    <dl class="dl-horizontal">
                        <dt>Nome Luogo</dt>
                        <dd>@Model.Name</dd>
                        <dt>Indirizzo</dt>
                        <dd>@Model.Address</dd>
                        <dt>Capacità</dt>
                        <dd>@Model.Capacity</dd>
                    </dl>
                </div>
                <div class="card-footer text-center">
                    @using (Html.BeginForm("Delete", "Venues", new { id = Model.VenueID }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-danger">Elimina</button>
                    }
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/Venues/Details.cshtml
@model GamingRoom.Models.Venues

@{
    ViewBag.Title = "Venue Details";
}

<div class="container" style="min-height:100vh">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card my-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Dettagli Luogo</h2>
                </div>
                <div class="card-body">
                    <dl class="row">

                        <dt class="col-sm-4">Immagine</dt>
                        <dd class="col-sm-8">
                            @if (!string.IsNullOrEmpty(Model.Photo))
                            {
                                <img src="@Url.Content("~/Content/ImgVenues/" + Model.Photo)" alt="Venue Image" style="max-width: 100%; height: auto;" />
                            }
                            else
                            {
                                <text>Nessuna Immagine disponibile</text>
                            }
                        </dd>
                        <dt class="col-sm-4">Nome</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Name)</dd>

                        <dt class="col-sm-4">Indirizzo</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Address)</dd>

                        <dt class="col-sm-4">Capacità</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Capacity) posti</dd>


                    </dl>
                </div>
                <div class="card-footer text-muted">
                    <a href="@Url.Action("Edit", new { id = Model.VenueID })" class="btn btn-primary">Modifica</a>
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Torna alla Lista</a>
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/Venues/Edit.cshtml
@model GamingRoom.Models.Venues

@{
    ViewBag.Title = "Edit Venue";
}

<div  style="height:100vh">
    
            <h2 class="text-center text-white mt-5">Modifica Sede</h2>
            @using (Html.BeginForm("Edit", "Venues", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal ms-5", role = "form" }))
            {
                @Html.AntiForgeryToken()

<div class="form-group text-white">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.VenueID)

    <div class="form-group">
        <label for="Name" class="col-md-2 control-label">Nome Sede</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="Address" class="col-md-2 control-label">Indirizzo</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="Capacity" class="col-md-2 control-label">Capacità</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @if (Model.Photo != null)
        {
            <div class="form-group">
                <label>Immagine Attuale:</label>
                <div>
                    <img src="@Url.Content("~/Content/ImgVenues/" + Model.Photo)" style="width:100px ; height:100px" />
                </div>
            </div>
        }


        <label for="image" class="col-md-2 control-label">Immagine</label>
        <div class="col-md-10">
            <input type="file" name="image" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salva" class="btn btn-primary" />
        </div>
    </div>
</div>

                <div class="mt-3">
                    @Html.ActionLink("Torna alla Lista", "Index", null, new { @class = "btn btn-secondary text-white ms-3" })
                </div>
            }
        </div>
    

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamingRoom/Views/Venues/Index.cshtml
@model IEnumerable<GamingRoom.Models.Venues>

@{
    ViewBag.Title = "Indice Luoghi";
}

<h2 class="text-center">Riepilogo Arene</h2>

<p>
    @Html.ActionLink("Crea Arena", "Create", null, new { @class = "btn btn-primary" })
</p>
<div class="table-responsive">
    <table class="table table-hover text-white fs-5">
        <thead class="bg-primary">
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Città
                </th>
                <th>
                    Capacità
                </th>
                <th>
                    Immagine
                </th>
                <th>Operazioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Capacity)
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.Photo))
                        {
                            <img src="@Url.Content("~/Content/ImgVenues/" + item.Photo)" alt="Immagine Luogo" class="img-fluid" style="max-width: 100px; height: auto;" />
                        }
                        else
                        {
                            <span>Nessuna</span>
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Modifica", "Edit", new { id = item.VenueID }, new { @class = "btn btn-info btn-sm" }) |
                        @Html.ActionLink("Dettagli", "Details", new { id = item.VenueID }, new { @class = "btn btn-primary btn-sm" }) |
                        @Html.ActionLink("Elimina", "Delete", new { id = item.VenueID }, new { @class = "btn btn-danger btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>