GamingRoom/Models/EventTitles.cs
namespace GamingRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class EventTitles
    {
        [Key]
        public int EventTitleID { get; set; }

        public int? EventID { get; set; }

        public int? TitleID { get; set; }

        public virtual Events Events { get; set; }

        public virtual Titles Titles { get; set; }
    }
}

GamingRoom/Controllers/EventTitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamingRoom.Models;

namespace GamingRoom.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    // Questo attributo specifica che solo gli utenti con il ruolo "SuperAdmin" possono accedere a questo controller.
    public class EventTitlesController : Controller
    {
        private ModelDBContext db = new ModelDBContext();

        // GET: EventTitles
        // Questo metodo gestisce la richiesta GET per visualizzare una lista di associazioni tra eventi e titoli.
        public ActionResult Index()
        {
            var eventTitles = db.EventTitles.Include(e => e.Events).Include(e => e.Titles);
            return View(eventTitles.ToList());
        }

        // GET: EventTitles/Details/5
        // Questo metodo gestisce la richiesta GET per visualizzare i dettagli di un'associazione tra evento e titolo.
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTitles eventTitles = db.EventTitles.Find(id);
            if (eventTitles == null)
            {
                return HttpNotFound();
            }
            return View(eventTitles);
        }

        // GET: EventTitles/Create
        // Questo metodo gestisce la richiesta GET per creare una nuova associazione tra evento e titolo.
        public ActionResult Create()
        {
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name");
            ViewBag.TitleID = new SelectList(db.Titles, "TitleID", "Name");
            return View();
        }

        // POST: EventTitles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        // Questo metodo gestisce la richiesta POST per creare una nuova associazione tra evento e titolo.
        public ActionResult Create([Bind(Include = "EventTitleID,EventID,TitleID")] EventTitles eventTitles)
        {
            if (ModelState.IsValid)
            {
                db.EventTitles.Add(eventTitles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", eventTitles.EventID);
            ViewBag.TitleID = new SelectList(db.Titles, "TitleID", "Name", eventTitles.TitleID);
            return View(eventTitles);
        }

        // GET: EventTitles/Edit/5
        // Questo metodo gestisce la richiesta GET per modificare un'associazione tra evento e titolo.
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTitles eventTitles = db.EventTitles.Find(id);
            if (eventTitles == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", eventTitles.EventID);
            ViewBag.TitleID = new SelectList(db.Titles, "TitleID", "Name", eventTitles.TitleID);
            return View(eventTitles);
        }

        // POST: EventTitles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        // Questo metodo gestisce la richiesta POST per modificare un'associazione tra evento e titolo.
        public ActionResult Edit([Bind(Include = "EventTitleID,EventID,TitleID")] EventTitles eventTitles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventTitles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", eventTitles.EventID);
            ViewBag.TitleID = new SelectList(db.Titles, "TitleID", "Name", eventTitles.TitleID);
            return View(eventTitles);
        }

        // GET: EventTitles/Delete/5
        // Questo metodo gestisce la richiesta GET per eliminare un'associazione tra evento e titolo.
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTitles eventTitles = db.EventTitles.Find(id);
            if (eventTitles == null)
            {
                return HttpNotFound();
            }
            return View(eventTitles);
        }

        // POST: EventTitles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        // Questo metodo gestisce la richiesta POST per confermare l'eliminazione di un'associazione tra evento e titolo.
        public ActionResult DeleteConfirmed(int id)
        {
            EventTitles eventTitles = db.EventTitles.Find(id);
            db.EventTitles.Remove(eventTitles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GamingRoom/Views/EventTitles/Create.cshtml
@model GamingRoom.Models.EventTitles

@{
    ViewBag.Title = "Create Event Title";
}

<h2 class="text-center">Crea Event Title</h2>

@using (Html.BeginForm("Create", "EventTitles", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal ms-5", @style = "height:100vh", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group text-white">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="EventID" class=" control-label col-md-2">Evento</label>
            <div class="col-md-10">
                @Html.DropDownList("EventID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="TitleID" class="control-label col-md-2">Titolo</label>
            <div class="col-md-10">
                @Html.DropDownList("TitleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TitleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
        <div>
            @Html.ActionLink("Torna alla lista", "Index", null, new { @class = "btn btn-default text-white" })
        </div>


    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamingRoom/Views/EventTitles/Delete.cshtml
@model GamingRoom.Models.EventTitles

@{
    ViewBag.Title = "Elimina Titolo Evento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="min-height:100vh">
    <div class="row justify-content-center align-items-center" style="height:100%">
        <div class="col-md-8">
            <div class="card mt-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Elimina Titolo Evento</h2>
                </div>
                <div class="card-body">
                    <h3 class="text-center">Sei sicuro di voler eliminare questo titolo evento?</h3>
                    <dl class="dl-horizontal">
                        <dt>Nome Evento</dt>
                        <dd>@Model.Events.Name</dd>
                        <dt>Titolo</dt>
                        <dd>@Model.Titles.Name</dd>
                    </dl>
                </div>
                <div class="card-footer text-center">
                   
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger">Elimina</button>
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Annulla</a>
                    
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/EventTitles/Details.cshtml
@model GamingRoom.Models.EventTitles

@{
    ViewBag.Title = "Details";
}

<div class="container" style="height:100vh">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card my-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Dettagli Titolo Evento</h2>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-4">Nome Evento</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Events.Name)</dd>

                        <dt class="col-sm-4">Nome Titolo</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Titles.Name)</dd>
                    </dl>
                </div>
                <div class="card-footer text-muted">
                    <a href="@Url.Action("Edit", new { id = Model.EventTitleID })" class="btn btn-primary">Modifica</a>
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Torna alla Lista</a>
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/EventTitles/Edit.cshtml
@model GamingRoom.Models.EventTitles

@{
    ViewBag.Title = "Edit";
}

<div  style="height:100vh">
    
            <h2 class="text-center text-white mt-5">Modifica Titolo Evento</h2>
            @using (Html.BeginForm("Edit", "EventTitles", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal ms-5", role = "form" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group text-white">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.EventTitleID)

                    <div class="form-group">
                        <label for="EventID" class="control-label col-md-2">Evento</label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.EventID, (SelectList)ViewBag.Events, "Scegli Evento", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EventID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="TitleID" class="control-label col-md-2">Titolo</label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.TitleID, (SelectList)ViewBag.Titles, "Scegli Titolo", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TitleID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Salva" class="btn btn-primary" />
                        </div>
                    </div>
                </div>

                <div>
                    @Html.ActionLink("Torna alla Lista", "Index", null, new { @class = "btn btn-secondary text-white ms-3" })
                </div>
            }
        </div>
   

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamingRoom/Views/EventTitles/Index.cshtml
@model IEnumerable<GamingRoom.Models.EventTitles>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Titoli ed Eventi</h2>

<p>
    @Html.ActionLink("Crea Nuovo", "Create", null, new { @class = "btn btn-primary ms-3" }) 
</p>
<div class="table-responsive" style="height:100vh">
    <table class="table table-hover text-white fs-5">
        <thead class="bg-primary">
            <tr>
                <th>
                    Nome Evento
                </th>
                <th>
                    Titolo Videogioco
                </th>
                <th></th> 
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Events.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titles.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Modifica", "Edit", new { id = item.EventTitleID }, new { @class = "btn btn-info btn-sm" }) |
                        @Html.ActionLink("Dettagli", "Details", new { id = item.EventTitleID }, new { @class = "btn btn-primary btn-sm" }) |
                        @Html.ActionLink("Elimina", "Delete", new { id = item.EventTitleID }, new { @class = "btn btn-danger btn-sm" })
                   </td>
                </tr>
            }
        </tbody>
    </table>
</div>