GamingRoom/Models/TeamRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GamingRoom.Models
{

    public class TeamRequest
    {
        [Key]
        public int TeamRequestId { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public string Description { get; set; }
        public string ProposedPhoto { get; set; }

        public int? CreatedBy { get; set; }


    }
}

GamingRoom/Controllers/TeamRequestsController.cs
using GamingRoom.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GamingRoom.Controllers
{
    public class TeamRequestsController : Controller
    {
        private ModelDBContext db = new ModelDBContext();

        // Metodo per creare una nuova richiesta di team
        public ActionResult Create()
        {
            ViewBag.CreatedBy = GetUsersList(); // Ottieni la lista degli utenti per il dropdown

            return View();
        }

        // Metodo per creare la lista di SelectListItem
        private IEnumerable<SelectListItem> GetUsersList()
        {
            return db.Users.Select(u => new SelectListItem
            {
                Value = u.UserID.ToString(),
                Text = u.Username 
            }).ToList();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Description,CreatedBy")] TeamRequest teamRequest, HttpPostedFileBase proposedPhoto)
        {
            if (ModelState.IsValid)
            {
                if (proposedPhoto != null && proposedPhoto.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(proposedPhoto.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/ImgTeams"), fileName);
                    proposedPhoto.SaveAs(path);
                    teamRequest.ProposedPhoto = fileName; // Salva il nome del file nel database
                }

                db.TeamRequests.Add(teamRequest);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.CreatedBy = GetUsersList(); // Mantieni il dropdown in caso di errore
            return View(teamRequest);
        }

        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Index()
        {
            return View(db.TeamRequests.ToList());
        }

        // Metodo per approvare una richiesta di team
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Approve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TeamRequest teamRequest = db.TeamRequests.Find(id);
            if (teamRequest == null)
            {
                return HttpNotFound();
            }

            Teams newTeam = new Teams
            {
                Name = teamRequest.Name,
                Description = teamRequest.Description,
                Photo = teamRequest.ProposedPhoto,
                CreatedBy = teamRequest.CreatedBy
            };

            db.Teams.Add(newTeam);
            db.TeamRequests.Remove(teamRequest);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // Metodo per eliminare una richiesta di team
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamRequest teamRequest = db.TeamRequests.Find(id);
            if (teamRequest == null)
            {
                return HttpNotFound();
            }
            return View(teamRequest);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            TeamRequest teamRequest = db.TeamRequests.Find(id);
            db.TeamRequests.Remove(teamRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GamingRoom/Views/TeamRequests/Approve.cshtml
@model GamingRoom.Models.TeamRequest

@{
    ViewBag.Title = "Approva Richiesta Team";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="container" style="min-height:100vh">
    <div class="row justify-content-center align-items-center" style="height:100%">
        <div class="col-md-8">
            <div class="card mt-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Dettagli Richiesta Team</h2>
                </div>
                <div class="card-body">
                    <dl class="dl-horizontal">
                        <dt>Nome Team</dt>
                        <dd>@Html.DisplayFor(model => model.Name)</dd>
                        <dt>Descrizione</dt>
                        <dd>@Html.DisplayFor(model => model.Description)</dd>
                        <dt>Foto Proposta</dt>
                        <dd>@Html.DisplayFor(model => model.ProposedPhoto)</dd>
                        <dt>Creato Da</dt>
                        <dd>@Html.DisplayFor(model => model.CreatedBy)</dd>
                    </dl>
                </div>
                <div class="card-footer text-center">
                    @using (Html.BeginForm("Approve", "TeamRequests", new { id = Model.TeamRequestId }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" value="Approva" class="btn btn-success">Approva Team</button>
                    }
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/TeamRequests/Create.cshtml
@model GamingRoom.Models.TeamRequest

@{
    ViewBag.Title = "Richiedi Creazione Team";
}

<h2 class="text-center">@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "TeamRequests", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal ms-4", @style = "height:100vh", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-group text-white">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label for="Name" class="control-label col-md-2">Nome Team</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="Description" class="control-label col-md-2">Descrizione</label>
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = 5 } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="CreatedBy" class="control-label col-md-2">Creato Da</label>
        <div class="col-md-10">
            @Html.DropDownList("CreatedBy", (IEnumerable<SelectListItem>)ViewBag.CreatedBy, "Seleziona Utente", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <label for="ProposedPhoto" class="control-label col-md-2">Foto del Team</label>
        <div class="col-md-10">
            <input type="file" name="ProposedPhoto" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Invia Richiesta" class="btn btn-primary" />
        </div>
    </div>
</div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GamingRoom/Views/TeamRequests/Delete.cshtml
@model GamingRoom.Models.TeamRequest

@{
    ViewBag.Title = "Elimina Richiesta di Team";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="min-height:100vh">
    <div class="row justify-content-center align-items-center" style="height:100%">
        <div class="col-md-8">
            <div class="card mt-5 text-white" style="background-color: rgb(157, 0, 255)!important">
                <div class="card-header">
                    <h2 class="text-center">Sei sicuro di voler eliminare questa richiesta di team?</h2>
                </div>
                <div class="card-body">
                    <dl class="dl-horizontal">
                        <dt>Nome Team</dt>
                        <dd>@Html.DisplayFor(model => model.Name)</dd>
                        <dt>Descrizione</dt>
                        <dd>@Html.DisplayFor(model => model.Description)</dd>
                        <dt>Foto Proposta</dt>
                        <dd>@Html.DisplayFor(model => model.ProposedPhoto)</dd>
                    </dl>
                </div>
                <div class="card-footer text-center">
                    @using (Html.BeginForm("Delete", "TeamRequests", new { id = Model.TeamRequestId }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-danger">Elimina</button>
                    }
                    <a href="@Url.Action("Index")" class="btn btn-secondary">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

GamingRoom/Views/TeamRequests/Index.cshtml
@model IEnumerable<GamingRoom.Models.TeamRequest>

@{
    ViewBag.Title = "Richieste di Team";
}

<h2 class="text-center">@ViewBag.Title</h2>

<div class="table-responsive" style="height:100vh">
    <table class="table table-hover text-white fs-5">
        <thead class="bg-primary">
            <tr>
                <th>Foto Proposta</th>
                <th>Nome Team</th>
                <th>Descrizione</th>
                
                <th>Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in Model)
            {
                <tr>
                    <td>
                        @if (!string.IsNullOrEmpty(request.ProposedPhoto))
                        {
                            <img src="@Url.Content("~/Content/ImgTeams/" + request.ProposedPhoto)" alt="Foto Team" class="img-thumbnail" style="max-width: 100px;" />
                        }
                    </td>

                    <td>@Html.DisplayFor(modelItem => request.Name)</td>
                    <td>@Html.DisplayFor(modelItem => request.Description)</td>

                    <td>
                        @Html.ActionLink("Approva", "Approve", new { id = request.TeamRequestId }, new { @class = "btn btn-success btn-sm" })
                        @Html.ActionLink("Elimina", "Delete", new { id = request.TeamRequestId }, new { @class = "btn btn-danger btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>